server.port=8081
spring.application.name=hotel-booking-backend
spring.datasource.url=jdbc:postgresql://ep-tiny-term-aoyw4t74-pooler.c-2.ap-southeast-1.aws.neon.tech/hotelmanagedb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7cd3LGQjKlbw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
app.cors.allowed-origins=https://crypticbrain.dilmith.live:8190,http://localhost:3000
app.jwt.secret=HotelBooking2026@NeonSecretKey!XY12
app.jwt.expiration=86400000
